import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;
public class ScannerMyCOCOR{
    private Grafo automata;
    private ArrayList<Token> tokens;

    public ScannerMyCOCOR(){}
   public String ValidarAutomata(String cadena){
        String cadenaDeTokens="";
        String caracteresEncontrados="";
        Token tokenLocal = new Token();
        int nodoActual=0;
        NodoGrafo nodoEvaluando=null;
        for (int i=0; i<cadena.length();i++){
           caracteresEncontrados+=cadena.charAt(i);
           nodoEvaluando = automata.getNodo(nodoActual);
           boolean transitioned=false;
           for (int j=0; j<nodoEvaluando.getTransiciones().size();j++){
                if(nodoEvaluando.getTransiciones().get(j).getParametro().contains(Character.toString(cadena.charAt(i)))){
                    nodoActual = nodoEvaluando.getTransiciones().get(j).getObjetivo();
                    transitioned=true;
                }
           }
           if(!transitioned){
                if(nodoEvaluando.getIsFinal()){
                    cadenaDeTokens+=(nodoEvaluando.getToken()+", ");
                    caracteresEncontrados=caracteresEncontrados.substring(0, caracteresEncontrados.length()-1);                    tokenLocal = new Token(nodoEvaluando.getTokenNumber(),nodoEvaluando.getToken(),  caracteresEncontrados);
                    tokens.add(tokenLocal);
                    caracteresEncontrados="";
                    i--;
                    nodoActual=0;
                }else{
                   return "Error de entrada. Entrada no valida";
                }
            }
           if(nodoEvaluando.getIsFinal()&&nodoEvaluando.getTokenType()==0){
                cadenaDeTokens+=(nodoEvaluando.getToken()+", ");
                caracteresEncontrados=caracteresEncontrados.substring(0, caracteresEncontrados.length()-1);                tokenLocal = new Token(nodoEvaluando.getTokenNumber(),nodoEvaluando.getToken(),  caracteresEncontrados);
                tokens.add(tokenLocal);
                caracteresEncontrados="";
                i--;
                nodoActual=0;
            }
        }
        nodoEvaluando = automata.getNodo(nodoActual);
        if(nodoEvaluando.getIsFinal()){
        tokenLocal = new Token(nodoEvaluando.getTokenNumber(), nodoEvaluando.getToken(), caracteresEncontrados);        tokens.add(tokenLocal);        cadenaDeTokens+=(nodoEvaluando.getToken());
        }
        return cadenaDeTokens;
    }
    public ArrayList<Token> GenerarTokenString(String cadenaAEvaluar)
    {
        tokens = new ArrayList<>();
        generateAutoma();
        String cadenaDeRetorno = ValidarAutomata(cadenaAEvaluar);
        System.out.println("Respuesta de automata: "+cadenaDeRetorno);
        return tokens;
   }
    private void generateAutoma(){
       automata = new Grafo();
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("nontoken");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(5);
		automata.addNode(0, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 0, "\n");
		automata.addTransicion(0, 0, "\n");
		automata.addTransicion(0, 0, "	");
		automata.addTransicion(0, 0, "\n\t ");
		automata.addNode(0, "\"");
		automata.addNode(0, "\'");
		automata.addNode(0, "C");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 1, "H");
		automata.addTransicion(0, 1, "R");
		automata.addNode(0, "(");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("(");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(20);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, ")");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken(")");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(21);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, ".");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken(".");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(14);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 1, "O");
		automata.addTransicion(0, 1, "M");
		automata.addNode(0, "P");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 1, "I");
		automata.addTransicion(0, 1, "L");
		automata.addNode(0, "E");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 1, "N");
		automata.addTransicion(0, 1, "D");
		automata.addNode(0, "A");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "T");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 1, "S");
		automata.addNode(0, "=");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("=");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(11);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "+");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("+");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(12);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "-");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("-");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(13);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "K");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(0, 1, "Y");
		automata.addTransicion(0, 1, "W");
		automata.addTransicion(0, 1, "U");
		automata.addTransicion(0, 1, "X");
		automata.addNode(0, "|");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("|");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(19);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "[");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("[");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(22);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "]");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("]");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(23);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "{");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("{");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(24);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "}");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("}");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(25);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, "<");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("<");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(26);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(0, ">");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken(">");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(27);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(1, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(1, "0123456789");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(1, 23, "C");
		automata.addTransicion(1, 23, "H");
		automata.addTransicion(1, 23, "R");
		automata.addTransicion(1, 23, "O");
		automata.addTransicion(1, 23, "M");
		automata.addTransicion(1, 23, "P");
		automata.addTransicion(1, 23, "I");
		automata.addTransicion(1, 23, "L");
		automata.addTransicion(1, 23, "E");
		automata.addTransicion(1, 23, "N");
		automata.addTransicion(1, 23, "D");
		automata.addTransicion(1, 23, "A");
		automata.addTransicion(1, 23, "T");
		automata.addTransicion(1, 23, "S");
		automata.addTransicion(1, 23, "K");
		automata.addTransicion(1, 23, "Y");
		automata.addTransicion(1, 23, "W");
		automata.addTransicion(1, 23, "U");
		automata.addTransicion(1, 23, "X");
		automata.addNode(2, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("string");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(1);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(2, 25, "0123456789");
		automata.addTransicion(2, 25, "\n");
		automata.addTransicion(2, 25, "\n");
		automata.addTransicion(2, 25, "	");
		automata.addTransicion(2, 25, "\n\t ");
		automata.addTransicion(2, 25, "\"");
		automata.addTransicion(2, 25, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\n\t\" ");
		automata.addTransicion(2, 25, "C");
		automata.addTransicion(2, 25, "H");
		automata.addTransicion(2, 25, "R");
		automata.addTransicion(2, 25, "O");
		automata.addTransicion(2, 25, "M");
		automata.addTransicion(2, 25, "P");
		automata.addTransicion(2, 25, "I");
		automata.addTransicion(2, 25, "L");
		automata.addTransicion(2, 25, "E");
		automata.addTransicion(2, 25, "N");
		automata.addTransicion(2, 25, "D");
		automata.addTransicion(2, 25, "A");
		automata.addTransicion(2, 25, "T");
		automata.addTransicion(2, 25, "S");
		automata.addTransicion(2, 25, "K");
		automata.addTransicion(2, 25, "Y");
		automata.addTransicion(2, 25, "W");
		automata.addTransicion(2, 25, "U");
		automata.addTransicion(2, 25, "X");
		automata.addNode(3, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addNode(3, "/");
		automata.addTransicion(3, 26, "C");
		automata.addTransicion(3, 26, "H");
		automata.addTransicion(3, 26, "R");
		automata.addTransicion(3, 26, "O");
		automata.addTransicion(3, 26, "M");
		automata.addTransicion(3, 26, "P");
		automata.addTransicion(3, 26, "I");
		automata.addTransicion(3, 26, "L");
		automata.addTransicion(3, 26, "E");
		automata.addTransicion(3, 26, "N");
		automata.addTransicion(3, 26, "D");
		automata.addTransicion(3, 26, "A");
		automata.addTransicion(3, 26, "T");
		automata.addTransicion(3, 26, "S");
		automata.addTransicion(3, 26, "K");
		automata.addTransicion(3, 26, "Y");
		automata.addTransicion(3, 26, "W");
		automata.addTransicion(3, 26, "U");
		automata.addTransicion(3, 26, "X");
		automata.addTransicion(4, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(4, 24, "0123456789");
		automata.addTransicion(4, 23, "C");
		automata.addNode(4, "H");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(4, 23, "R");
		automata.addNode(4, "O");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(4, 23, "M");
		automata.addTransicion(4, 23, "P");
		automata.addTransicion(4, 23, "I");
		automata.addTransicion(4, 23, "L");
		automata.addTransicion(4, 23, "E");
		automata.addTransicion(4, 23, "N");
		automata.addTransicion(4, 23, "D");
		automata.addTransicion(4, 23, "A");
		automata.addTransicion(4, 23, "T");
		automata.addTransicion(4, 23, "S");
		automata.addTransicion(4, 23, "K");
		automata.addTransicion(4, 23, "Y");
		automata.addTransicion(4, 23, "W");
		automata.addTransicion(4, 23, "U");
		automata.addTransicion(4, 23, "X");
		automata.addNode(5, ".");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("startcode");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(6);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addNode(7, ")");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("endcode");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(7);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(8, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(8, 24, "0123456789");
		automata.addTransicion(8, 23, "C");
		automata.addTransicion(8, 23, "H");
		automata.addNode(8, "R");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(8, 23, "O");
		automata.addTransicion(8, 23, "M");
		automata.addTransicion(8, 23, "P");
		automata.addTransicion(8, 23, "I");
		automata.addTransicion(8, 23, "L");
		automata.addTransicion(8, 23, "E");
		automata.addTransicion(8, 23, "N");
		automata.addTransicion(8, 23, "D");
		automata.addTransicion(8, 23, "A");
		automata.addTransicion(8, 23, "T");
		automata.addTransicion(8, 23, "S");
		automata.addTransicion(8, 23, "K");
		automata.addTransicion(8, 23, "Y");
		automata.addTransicion(8, 23, "W");
		automata.addTransicion(8, 23, "U");
		automata.addTransicion(8, 23, "X");
		automata.addTransicion(9, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(9, 24, "0123456789");
		automata.addTransicion(9, 23, "C");
		automata.addTransicion(9, 23, "H");
		automata.addTransicion(9, 23, "R");
		automata.addTransicion(9, 23, "O");
		automata.addTransicion(9, 23, "M");
		automata.addTransicion(9, 23, "P");
		automata.addTransicion(9, 23, "I");
		automata.addTransicion(9, 23, "L");
		automata.addTransicion(9, 23, "E");
		automata.addNode(9, "N");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(9, 23, "D");
		automata.addTransicion(9, 23, "A");
		automata.addTransicion(9, 23, "T");
		automata.addTransicion(9, 23, "S");
		automata.addTransicion(9, 23, "K");
		automata.addTransicion(9, 23, "Y");
		automata.addTransicion(9, 23, "W");
		automata.addTransicion(9, 23, "U");
		automata.addNode(9, "X");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(10, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(10, 24, "0123456789");
		automata.addTransicion(10, 23, "C");
		automata.addTransicion(10, 23, "H");
		automata.addTransicion(10, 23, "R");
		automata.addTransicion(10, 23, "O");
		automata.addTransicion(10, 23, "M");
		automata.addTransicion(10, 23, "P");
		automata.addTransicion(10, 23, "I");
		automata.addTransicion(10, 23, "L");
		automata.addTransicion(10, 23, "E");
		automata.addNode(10, "N");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(10, 23, "D");
		automata.addTransicion(10, 23, "A");
		automata.addTransicion(10, 23, "T");
		automata.addTransicion(10, 23, "S");
		automata.addTransicion(10, 23, "K");
		automata.addTransicion(10, 23, "Y");
		automata.addTransicion(10, 23, "W");
		automata.addTransicion(10, 23, "U");
		automata.addTransicion(10, 23, "X");
		automata.addTransicion(11, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(11, 24, "0123456789");
		automata.addTransicion(11, 23, "C");
		automata.addTransicion(11, 23, "H");
		automata.addTransicion(11, 23, "R");
		automata.addNode(11, "O");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(11, 23, "M");
		automata.addTransicion(11, 23, "P");
		automata.addTransicion(11, 23, "I");
		automata.addTransicion(11, 23, "L");
		automata.addTransicion(11, 23, "E");
		automata.addTransicion(11, 23, "N");
		automata.addTransicion(11, 23, "D");
		automata.addTransicion(11, 23, "A");
		automata.addTransicion(11, 23, "T");
		automata.addTransicion(11, 23, "S");
		automata.addTransicion(11, 23, "K");
		automata.addTransicion(11, 23, "Y");
		automata.addTransicion(11, 23, "W");
		automata.addTransicion(11, 23, "U");
		automata.addTransicion(11, 23, "X");
		automata.addTransicion(15, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(15, 24, "0123456789");
		automata.addTransicion(15, 23, "C");
		automata.addTransicion(15, 23, "H");
		automata.addTransicion(15, 23, "R");
		automata.addTransicion(15, 23, "O");
		automata.addTransicion(15, 23, "M");
		automata.addTransicion(15, 23, "P");
		automata.addTransicion(15, 23, "I");
		automata.addTransicion(15, 23, "L");
		automata.addNode(15, "E");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(15, 23, "N");
		automata.addTransicion(15, 23, "D");
		automata.addTransicion(15, 23, "A");
		automata.addTransicion(15, 23, "T");
		automata.addTransicion(15, 23, "S");
		automata.addTransicion(15, 23, "K");
		automata.addTransicion(15, 23, "Y");
		automata.addTransicion(15, 23, "W");
		automata.addTransicion(15, 23, "U");
		automata.addTransicion(15, 23, "X");
		automata.addTransicion(23, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(23, 24, "0123456789");
		automata.addTransicion(23, 23, "C");
		automata.addTransicion(23, 23, "H");
		automata.addTransicion(23, 23, "R");
		automata.addTransicion(23, 23, "O");
		automata.addTransicion(23, 23, "M");
		automata.addTransicion(23, 23, "P");
		automata.addTransicion(23, 23, "I");
		automata.addTransicion(23, 23, "L");
		automata.addTransicion(23, 23, "E");
		automata.addTransicion(23, 23, "N");
		automata.addTransicion(23, 23, "D");
		automata.addTransicion(23, 23, "A");
		automata.addTransicion(23, 23, "T");
		automata.addTransicion(23, 23, "S");
		automata.addTransicion(23, 23, "K");
		automata.addTransicion(23, 23, "Y");
		automata.addTransicion(23, 23, "W");
		automata.addTransicion(23, 23, "U");
		automata.addTransicion(23, 23, "X");
		automata.addTransicion(24, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(24, 24, "0123456789");
		automata.addTransicion(24, 23, "C");
		automata.addTransicion(24, 23, "H");
		automata.addTransicion(24, 23, "R");
		automata.addTransicion(24, 23, "O");
		automata.addTransicion(24, 23, "M");
		automata.addTransicion(24, 23, "P");
		automata.addTransicion(24, 23, "I");
		automata.addTransicion(24, 23, "L");
		automata.addTransicion(24, 23, "E");
		automata.addTransicion(24, 23, "N");
		automata.addTransicion(24, 23, "D");
		automata.addTransicion(24, 23, "A");
		automata.addTransicion(24, 23, "T");
		automata.addTransicion(24, 23, "S");
		automata.addTransicion(24, 23, "K");
		automata.addTransicion(24, 23, "Y");
		automata.addTransicion(24, 23, "W");
		automata.addTransicion(24, 23, "U");
		automata.addTransicion(24, 23, "X");
		automata.addNode(25, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("string");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(1);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(25, 38, "0123456789");
		automata.addTransicion(25, 38, "\n");
		automata.addTransicion(25, 38, "\n");
		automata.addTransicion(25, 38, "\t");
		automata.addTransicion(25, 38, "\n\t ");
		automata.addTransicion(25, 38, "\"");
		automata.addTransicion(25, 38, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\n\t\" ");
		automata.addTransicion(25, 38, "C");
		automata.addTransicion(25, 38, "H");
		automata.addTransicion(25, 38, "R");
		automata.addTransicion(25, 38, "O");
		automata.addTransicion(25, 38, "M");
		automata.addTransicion(25, 38, "P");
		automata.addTransicion(25, 38, "I");
		automata.addTransicion(25, 38, "L");
		automata.addTransicion(25, 38, "E");
		automata.addTransicion(25, 38, "N");
		automata.addTransicion(25, 38, "D");
		automata.addTransicion(25, 38, "A");
		automata.addTransicion(25, 38, "T");
		automata.addTransicion(25, 38, "S");
		automata.addTransicion(25, 38, "K");
		automata.addTransicion(25, 38, "Y");
		automata.addTransicion(25, 38, "W");
		automata.addTransicion(25, 38, "U");
		automata.addTransicion(25, 38, "X");
		automata.addNode(26, "'");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("char");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(2);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(27, 26, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(27, 26, "C");
		automata.addTransicion(27, 26, "H");
		automata.addTransicion(27, 26, "R");
		automata.addTransicion(27, 26, "O");
		automata.addTransicion(27, 26, "M");
		automata.addTransicion(27, 26, "P");
		automata.addTransicion(27, 26, "I");
		automata.addTransicion(27, 26, "L");
		automata.addTransicion(27, 26, "E");
		automata.addTransicion(27, 26, "N");
		automata.addTransicion(27, 26, "D");
		automata.addTransicion(27, 26, "A");
		automata.addTransicion(27, 26, "T");
		automata.addTransicion(27, 26, "S");
		automata.addTransicion(27, 26, "K");
		automata.addTransicion(27, 26, "Y");
		automata.addTransicion(27, 26, "W");
		automata.addTransicion(27, 26, "U");
		automata.addTransicion(27, 26, "X");
		automata.addTransicion(28, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(28, 24, "0123456789");
		automata.addTransicion(28, 23, "C");
		automata.addTransicion(28, 23, "H");
		automata.addNode(28, "R");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(28, 23, "O");
		automata.addTransicion(28, 23, "M");
		automata.addTransicion(28, 23, "P");
		automata.addTransicion(28, 23, "I");
		automata.addTransicion(28, 23, "L");
		automata.addTransicion(28, 23, "E");
		automata.addTransicion(28, 23, "N");
		automata.addTransicion(28, 23, "D");
		automata.addNode(28, "A");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(28, 23, "T");
		automata.addTransicion(28, 23, "S");
		automata.addTransicion(28, 23, "K");
		automata.addTransicion(28, 23, "Y");
		automata.addTransicion(28, 23, "W");
		automata.addTransicion(28, 23, "U");
		automata.addTransicion(28, 23, "X");
		automata.addTransicion(29, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(29, 24, "0123456789");
		automata.addTransicion(29, 23, "C");
		automata.addTransicion(29, 23, "H");
		automata.addTransicion(29, 23, "R");
		automata.addTransicion(29, 23, "O");
		automata.addNode(29, "M");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(29, 23, "P");
		automata.addTransicion(29, 23, "I");
		automata.addTransicion(29, 23, "L");
		automata.addTransicion(29, 23, "E");
		automata.addTransicion(29, 23, "N");
		automata.addTransicion(29, 23, "D");
		automata.addTransicion(29, 23, "A");
		automata.addTransicion(29, 23, "T");
		automata.addTransicion(29, 23, "S");
		automata.addTransicion(29, 23, "K");
		automata.addTransicion(29, 23, "Y");
		automata.addTransicion(29, 23, "W");
		automata.addTransicion(29, 23, "U");
		automata.addTransicion(29, 23, "X");
		automata.addTransicion(32, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(32, 24, "0123456789");
		automata.addTransicion(32, 23, "C");
		automata.addTransicion(32, 23, "H");
		automata.addTransicion(32, 23, "R");
		automata.addNode(32, "O");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(32, 23, "M");
		automata.addTransicion(32, 23, "P");
		automata.addTransicion(32, 23, "I");
		automata.addTransicion(32, 23, "L");
		automata.addTransicion(32, 23, "E");
		automata.addTransicion(32, 23, "N");
		automata.addTransicion(32, 23, "D");
		automata.addTransicion(32, 23, "A");
		automata.addTransicion(32, 23, "T");
		automata.addTransicion(32, 23, "S");
		automata.addTransicion(32, 23, "K");
		automata.addTransicion(32, 23, "Y");
		automata.addTransicion(32, 23, "W");
		automata.addTransicion(32, 23, "U");
		automata.addTransicion(32, 23, "X");
		automata.addTransicion(33, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(33, 24, "0123456789");
		automata.addTransicion(33, 23, "C");
		automata.addTransicion(33, 23, "H");
		automata.addTransicion(33, 23, "R");
		automata.addTransicion(33, 23, "O");
		automata.addTransicion(33, 23, "M");
		automata.addTransicion(33, 23, "P");
		automata.addTransicion(33, 23, "I");
		automata.addTransicion(33, 23, "L");
		automata.addTransicion(33, 23, "E");
		automata.addTransicion(33, 23, "N");
		automata.addNode(33, "D");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("END");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(9);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(33, 23, "A");
		automata.addTransicion(33, 23, "T");
		automata.addTransicion(33, 23, "S");
		automata.addTransicion(33, 23, "K");
		automata.addTransicion(33, 23, "Y");
		automata.addTransicion(33, 23, "W");
		automata.addTransicion(33, 23, "U");
		automata.addTransicion(33, 23, "X");
		automata.addTransicion(34, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(34, 24, "0123456789");
		automata.addNode(34, "C");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(34, 23, "H");
		automata.addTransicion(34, 23, "R");
		automata.addTransicion(34, 23, "O");
		automata.addTransicion(34, 23, "M");
		automata.addTransicion(34, 23, "P");
		automata.addTransicion(34, 23, "I");
		automata.addTransicion(34, 23, "L");
		automata.addTransicion(34, 23, "E");
		automata.addTransicion(34, 23, "N");
		automata.addTransicion(34, 23, "D");
		automata.addTransicion(34, 23, "A");
		automata.addTransicion(34, 23, "T");
		automata.addTransicion(34, 23, "S");
		automata.addTransicion(34, 23, "K");
		automata.addTransicion(34, 23, "Y");
		automata.addTransicion(34, 23, "W");
		automata.addTransicion(34, 23, "U");
		automata.addTransicion(34, 23, "X");
		automata.addTransicion(35, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(35, 24, "0123456789");
		automata.addTransicion(35, 23, "C");
		automata.addTransicion(35, 23, "H");
		automata.addTransicion(35, 23, "R");
		automata.addTransicion(35, 23, "O");
		automata.addTransicion(35, 23, "M");
		automata.addTransicion(35, 23, "P");
		automata.addTransicion(35, 23, "I");
		automata.addTransicion(35, 23, "L");
		automata.addTransicion(35, 23, "E");
		automata.addTransicion(35, 23, "N");
		automata.addTransicion(35, 23, "D");
		automata.addTransicion(35, 23, "A");
		automata.addTransicion(35, 23, "T");
		automata.addTransicion(35, 23, "S");
		automata.addTransicion(35, 23, "K");
		automata.addNode(35, "Y");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ANY");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(28);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(35, 23, "W");
		automata.addTransicion(35, 23, "U");
		automata.addTransicion(35, 23, "X");
		automata.addTransicion(36, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(36, 24, "0123456789");
		automata.addTransicion(36, 23, "C");
		automata.addTransicion(36, 23, "H");
		automata.addTransicion(36, 23, "R");
		automata.addTransicion(36, 23, "O");
		automata.addTransicion(36, 23, "M");
		automata.addTransicion(36, 23, "P");
		automata.addTransicion(36, 23, "I");
		automata.addTransicion(36, 23, "L");
		automata.addTransicion(36, 23, "E");
		automata.addTransicion(36, 23, "N");
		automata.addTransicion(36, 23, "D");
		automata.addTransicion(36, 23, "A");
		automata.addTransicion(36, 23, "T");
		automata.addTransicion(36, 23, "S");
		automata.addNode(36, "K");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(36, 23, "Y");
		automata.addTransicion(36, 23, "W");
		automata.addTransicion(36, 23, "U");
		automata.addTransicion(36, 23, "X");
		automata.addTransicion(37, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(37, 24, "0123456789");
		automata.addTransicion(37, 23, "C");
		automata.addTransicion(37, 23, "H");
		automata.addTransicion(37, 23, "R");
		automata.addTransicion(37, 23, "O");
		automata.addTransicion(37, 23, "M");
		automata.addTransicion(37, 23, "P");
		automata.addTransicion(37, 23, "I");
		automata.addTransicion(37, 23, "L");
		automata.addTransicion(37, 23, "E");
		automata.addTransicion(37, 23, "N");
		automata.addTransicion(37, 23, "D");
		automata.addTransicion(37, 23, "A");
		automata.addTransicion(37, 23, "T");
		automata.addTransicion(37, 23, "S");
		automata.addTransicion(37, 23, "K");
		automata.addNode(37, "Y");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(37, 23, "W");
		automata.addTransicion(37, 23, "U");
		automata.addTransicion(37, 23, "X");
		automata.addTransicion(38, 38, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(38, 38, "0123456789");
		automata.addTransicion(38, 38, "\n");
		automata.addTransicion(38, 38, "\n");
		automata.addTransicion(38, 38, "\t");
		automata.addTransicion(38, 38, "\n\t ");
		automata.addTransicion(38, 38, "\"");
		automata.addTransicion(38, 38, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\n\t\" ");
		automata.addTransicion(38, 38, "C");
		automata.addTransicion(38, 38, "H");
		automata.addTransicion(38, 38, "R");
		automata.addTransicion(38, 38, "O");
		automata.addTransicion(38, 38, "M");
		automata.addTransicion(38, 38, "P");
		automata.addTransicion(38, 38, "I");
		automata.addTransicion(38, 38, "L");
		automata.addTransicion(38, 38, "E");
		automata.addTransicion(38, 38, "N");
		automata.addTransicion(38, 38, "D");
		automata.addTransicion(38, 38, "A");
		automata.addTransicion(38, 38, "T");
		automata.addTransicion(38, 38, "S");
		automata.addTransicion(38, 38, "K");
		automata.addTransicion(38, 38, "Y");
		automata.addTransicion(38, 38, "W");
		automata.addTransicion(38, 38, "U");
		automata.addTransicion(38, 38, "X");
		automata.addTransicion(40, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(40, 24, "0123456789");
		automata.addTransicion(40, 23, "C");
		automata.addTransicion(40, 23, "H");
		automata.addTransicion(40, 23, "R");
		automata.addNode(40, "(");
		automata.addTransicion(40, 23, "O");
		automata.addTransicion(40, 23, "M");
		automata.addTransicion(40, 23, "P");
		automata.addTransicion(40, 23, "I");
		automata.addTransicion(40, 23, "L");
		automata.addTransicion(40, 23, "E");
		automata.addTransicion(40, 23, "N");
		automata.addTransicion(40, 23, "D");
		automata.addTransicion(40, 23, "A");
		automata.addTransicion(40, 23, "T");
		automata.addTransicion(40, 23, "S");
		automata.addTransicion(40, 23, "K");
		automata.addTransicion(40, 23, "Y");
		automata.addTransicion(40, 23, "W");
		automata.addTransicion(40, 23, "U");
		automata.addTransicion(40, 23, "X");
		automata.addTransicion(41, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(41, 24, "0123456789");
		automata.addTransicion(41, 23, "C");
		automata.addTransicion(41, 23, "H");
		automata.addNode(41, "R");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(41, 23, "O");
		automata.addTransicion(41, 23, "M");
		automata.addTransicion(41, 23, "P");
		automata.addTransicion(41, 23, "I");
		automata.addTransicion(41, 23, "L");
		automata.addTransicion(41, 23, "E");
		automata.addTransicion(41, 23, "N");
		automata.addTransicion(41, 23, "D");
		automata.addTransicion(41, 23, "A");
		automata.addTransicion(41, 23, "T");
		automata.addTransicion(41, 23, "S");
		automata.addTransicion(41, 23, "K");
		automata.addTransicion(41, 23, "Y");
		automata.addTransicion(41, 23, "W");
		automata.addTransicion(41, 23, "U");
		automata.addTransicion(41, 23, "X");
		automata.addTransicion(42, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(42, 24, "0123456789");
		automata.addTransicion(42, 23, "C");
		automata.addTransicion(42, 23, "H");
		automata.addTransicion(42, 23, "R");
		automata.addTransicion(42, 23, "O");
		automata.addTransicion(42, 23, "M");
		automata.addNode(42, "P");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(42, 23, "I");
		automata.addTransicion(42, 23, "L");
		automata.addTransicion(42, 23, "E");
		automata.addTransicion(42, 23, "N");
		automata.addTransicion(42, 23, "D");
		automata.addTransicion(42, 23, "A");
		automata.addTransicion(42, 23, "T");
		automata.addTransicion(42, 23, "S");
		automata.addTransicion(42, 23, "K");
		automata.addTransicion(42, 23, "Y");
		automata.addTransicion(42, 23, "W");
		automata.addTransicion(42, 23, "U");
		automata.addTransicion(42, 23, "X");
		automata.addTransicion(43, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(43, 24, "0123456789");
		automata.addTransicion(43, 23, "C");
		automata.addTransicion(43, 23, "H");
		automata.addTransicion(43, 23, "R");
		automata.addTransicion(43, 23, "O");
		automata.addTransicion(43, 23, "M");
		automata.addTransicion(43, 23, "P");
		automata.addTransicion(43, 23, "I");
		automata.addTransicion(43, 23, "L");
		automata.addTransicion(43, 23, "E");
		automata.addTransicion(43, 23, "N");
		automata.addNode(43, "D");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(43, 23, "A");
		automata.addTransicion(43, 23, "T");
		automata.addTransicion(43, 23, "S");
		automata.addTransicion(43, 23, "K");
		automata.addTransicion(43, 23, "Y");
		automata.addTransicion(43, 23, "W");
		automata.addTransicion(43, 23, "U");
		automata.addTransicion(43, 23, "X");
		automata.addTransicion(44, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(44, 24, "0123456789");
		automata.addTransicion(44, 23, "C");
		automata.addTransicion(44, 23, "H");
		automata.addTransicion(44, 23, "R");
		automata.addTransicion(44, 23, "O");
		automata.addTransicion(44, 23, "M");
		automata.addTransicion(44, 23, "P");
		automata.addTransicion(44, 23, "I");
		automata.addTransicion(44, 23, "L");
		automata.addTransicion(44, 23, "E");
		automata.addTransicion(44, 23, "N");
		automata.addTransicion(44, 23, "D");
		automata.addTransicion(44, 23, "A");
		automata.addTransicion(44, 23, "T");
		automata.addTransicion(44, 23, "S");
		automata.addTransicion(44, 23, "K");
		automata.addTransicion(44, 23, "Y");
		automata.addTransicion(44, 23, "W");
		automata.addTransicion(44, 23, "U");
		automata.addTransicion(44, 23, "X");
		automata.addTransicion(45, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(45, 24, "0123456789");
		automata.addTransicion(45, 23, "C");
		automata.addTransicion(45, 23, "H");
		automata.addTransicion(45, 23, "R");
		automata.addTransicion(45, 23, "O");
		automata.addTransicion(45, 23, "M");
		automata.addTransicion(45, 23, "P");
		automata.addTransicion(45, 23, "I");
		automata.addTransicion(45, 23, "L");
		automata.addNode(45, "E");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(45, 23, "N");
		automata.addTransicion(45, 23, "D");
		automata.addTransicion(45, 23, "A");
		automata.addTransicion(45, 23, "T");
		automata.addTransicion(45, 23, "S");
		automata.addTransicion(45, 23, "K");
		automata.addTransicion(45, 23, "Y");
		automata.addTransicion(45, 23, "W");
		automata.addTransicion(45, 23, "U");
		automata.addTransicion(45, 23, "X");
		automata.addTransicion(46, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(46, 24, "0123456789");
		automata.addTransicion(46, 23, "C");
		automata.addTransicion(46, 23, "H");
		automata.addTransicion(46, 23, "R");
		automata.addTransicion(46, 23, "O");
		automata.addTransicion(46, 23, "M");
		automata.addTransicion(46, 23, "P");
		automata.addTransicion(46, 23, "I");
		automata.addTransicion(46, 23, "L");
		automata.addTransicion(46, 23, "E");
		automata.addTransicion(46, 23, "N");
		automata.addTransicion(46, 23, "D");
		automata.addTransicion(46, 23, "A");
		automata.addTransicion(46, 23, "T");
		automata.addTransicion(46, 23, "S");
		automata.addTransicion(46, 23, "K");
		automata.addTransicion(46, 23, "Y");
		automata.addTransicion(46, 23, "W");
		automata.addTransicion(46, 23, "U");
		automata.addTransicion(46, 23, "X");
		automata.addTransicion(47, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(47, 24, "0123456789");
		automata.addTransicion(47, 23, "C");
		automata.addTransicion(47, 23, "H");
		automata.addTransicion(47, 23, "R");
		automata.addTransicion(47, 23, "O");
		automata.addTransicion(47, 23, "M");
		automata.addTransicion(47, 23, "P");
		automata.addTransicion(47, 23, "I");
		automata.addTransicion(47, 23, "L");
		automata.addNode(47, "E");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(47, 23, "N");
		automata.addTransicion(47, 23, "D");
		automata.addTransicion(47, 23, "A");
		automata.addTransicion(47, 23, "T");
		automata.addTransicion(47, 23, "S");
		automata.addTransicion(47, 23, "K");
		automata.addTransicion(47, 23, "Y");
		automata.addTransicion(47, 23, "W");
		automata.addTransicion(47, 23, "U");
		automata.addTransicion(47, 23, "X");
		automata.addTransicion(48, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(48, 24, "0123456789");
		automata.addTransicion(48, 23, "C");
		automata.addTransicion(48, 23, "H");
		automata.addTransicion(48, 23, "R");
		automata.addTransicion(48, 23, "O");
		automata.addTransicion(48, 23, "M");
		automata.addTransicion(48, 23, "P");
		automata.addTransicion(48, 23, "I");
		automata.addTransicion(48, 23, "L");
		automata.addTransicion(48, 23, "E");
		automata.addTransicion(48, 23, "N");
		automata.addTransicion(48, 23, "D");
		automata.addTransicion(48, 23, "A");
		automata.addTransicion(48, 23, "T");
		automata.addTransicion(48, 23, "S");
		automata.addTransicion(48, 23, "K");
		automata.addTransicion(48, 23, "Y");
		automata.addNode(48, "W");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(48, 23, "U");
		automata.addTransicion(48, 23, "X");
		automata.addNode(49, "0123456789");
		automata.addTransicion(50, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(50, 24, "0123456789");
		automata.addTransicion(50, 23, "C");
		automata.addTransicion(50, 23, "H");
		automata.addTransicion(50, 23, "R");
		automata.addTransicion(50, 23, "O");
		automata.addTransicion(50, 23, "M");
		automata.addTransicion(50, 23, "P");
		automata.addTransicion(50, 23, "I");
		automata.addTransicion(50, 23, "L");
		automata.addTransicion(50, 23, "E");
		automata.addTransicion(50, 23, "N");
		automata.addTransicion(50, 23, "D");
		automata.addNode(50, "A");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(50, 23, "T");
		automata.addTransicion(50, 23, "S");
		automata.addTransicion(50, 23, "K");
		automata.addTransicion(50, 23, "Y");
		automata.addTransicion(50, 23, "W");
		automata.addTransicion(50, 23, "U");
		automata.addTransicion(50, 23, "X");
		automata.addTransicion(51, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(51, 24, "0123456789");
		automata.addTransicion(51, 23, "C");
		automata.addTransicion(51, 23, "H");
		automata.addTransicion(51, 23, "R");
		automata.addTransicion(51, 23, "O");
		automata.addTransicion(51, 23, "M");
		automata.addTransicion(51, 23, "P");
		automata.addNode(51, "I");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(51, 23, "L");
		automata.addTransicion(51, 23, "E");
		automata.addTransicion(51, 23, "N");
		automata.addTransicion(51, 23, "D");
		automata.addTransicion(51, 23, "A");
		automata.addTransicion(51, 23, "T");
		automata.addTransicion(51, 23, "S");
		automata.addTransicion(51, 23, "K");
		automata.addTransicion(51, 23, "Y");
		automata.addTransicion(51, 23, "W");
		automata.addTransicion(51, 23, "U");
		automata.addTransicion(51, 23, "X");
		automata.addTransicion(52, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(52, 24, "0123456789");
		automata.addTransicion(52, 23, "C");
		automata.addTransicion(52, 23, "H");
		automata.addTransicion(52, 23, "R");
		automata.addTransicion(52, 23, "O");
		automata.addTransicion(52, 23, "M");
		automata.addTransicion(52, 23, "P");
		automata.addTransicion(52, 23, "I");
		automata.addTransicion(52, 23, "L");
		automata.addTransicion(52, 23, "E");
		automata.addTransicion(52, 23, "N");
		automata.addTransicion(52, 23, "D");
		automata.addTransicion(52, 23, "A");
		automata.addTransicion(52, 23, "T");
		automata.addTransicion(52, 23, "S");
		automata.addTransicion(52, 23, "K");
		automata.addTransicion(52, 23, "Y");
		automata.addTransicion(52, 23, "W");
		automata.addNode(52, "U");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(52, 23, "X");
		automata.addTransicion(53, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(53, 24, "0123456789");
		automata.addTransicion(53, 23, "C");
		automata.addTransicion(53, 23, "H");
		automata.addTransicion(53, 23, "R");
		automata.addTransicion(53, 23, "O");
		automata.addTransicion(53, 23, "M");
		automata.addNode(53, "P");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(53, 23, "I");
		automata.addTransicion(53, 23, "L");
		automata.addTransicion(53, 23, "E");
		automata.addTransicion(53, 23, "N");
		automata.addTransicion(53, 23, "D");
		automata.addTransicion(53, 23, "A");
		automata.addTransicion(53, 23, "T");
		automata.addTransicion(53, 23, "S");
		automata.addTransicion(53, 23, "K");
		automata.addTransicion(53, 23, "Y");
		automata.addTransicion(53, 23, "W");
		automata.addTransicion(53, 23, "U");
		automata.addTransicion(53, 23, "X");
		automata.addTransicion(54, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(54, 24, "0123456789");
		automata.addTransicion(54, 23, "C");
		automata.addTransicion(54, 23, "H");
		automata.addTransicion(54, 23, "R");
		automata.addTransicion(54, 23, "O");
		automata.addTransicion(54, 23, "M");
		automata.addTransicion(54, 23, "P");
		automata.addTransicion(54, 23, "I");
		automata.addTransicion(54, 23, "L");
		automata.addTransicion(54, 23, "E");
		automata.addNode(54, "N");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(54, 23, "D");
		automata.addTransicion(54, 23, "A");
		automata.addTransicion(54, 23, "T");
		automata.addTransicion(54, 23, "S");
		automata.addTransicion(54, 23, "K");
		automata.addTransicion(54, 23, "Y");
		automata.addTransicion(54, 23, "W");
		automata.addTransicion(54, 23, "U");
		automata.addTransicion(54, 23, "X");
		automata.addTransicion(55, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(55, 24, "0123456789");
		automata.addTransicion(55, 23, "C");
		automata.addTransicion(55, 23, "H");
		automata.addTransicion(55, 23, "R");
		automata.addNode(55, "O");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(55, 23, "M");
		automata.addTransicion(55, 23, "P");
		automata.addTransicion(55, 23, "I");
		automata.addTransicion(55, 23, "L");
		automata.addTransicion(55, 23, "E");
		automata.addTransicion(55, 23, "N");
		automata.addTransicion(55, 23, "D");
		automata.addTransicion(55, 23, "A");
		automata.addTransicion(55, 23, "T");
		automata.addTransicion(55, 23, "S");
		automata.addTransicion(55, 23, "K");
		automata.addTransicion(55, 23, "Y");
		automata.addTransicion(55, 23, "W");
		automata.addTransicion(55, 23, "U");
		automata.addTransicion(55, 23, "X");
		automata.addNode(56, "0123456789");
		automata.addNode(56, ")");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("charnumber");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(3);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(57, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(57, 24, "0123456789");
		automata.addNode(57, "C");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(57, 23, "H");
		automata.addTransicion(57, 23, "R");
		automata.addTransicion(57, 23, "O");
		automata.addTransicion(57, 23, "M");
		automata.addTransicion(57, 23, "P");
		automata.addTransicion(57, 23, "I");
		automata.addTransicion(57, 23, "L");
		automata.addTransicion(57, 23, "E");
		automata.addTransicion(57, 23, "N");
		automata.addTransicion(57, 23, "D");
		automata.addTransicion(57, 23, "A");
		automata.addTransicion(57, 23, "T");
		automata.addTransicion(57, 23, "S");
		automata.addTransicion(57, 23, "K");
		automata.addTransicion(57, 23, "Y");
		automata.addTransicion(57, 23, "W");
		automata.addTransicion(57, 23, "U");
		automata.addTransicion(57, 23, "X");
		automata.addTransicion(58, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(58, 24, "0123456789");
		automata.addTransicion(58, 23, "C");
		automata.addTransicion(58, 23, "H");
		automata.addTransicion(58, 23, "R");
		automata.addTransicion(58, 23, "O");
		automata.addTransicion(58, 23, "M");
		automata.addTransicion(58, 23, "P");
		automata.addTransicion(58, 23, "I");
		automata.addNode(58, "L");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(58, 23, "E");
		automata.addTransicion(58, 23, "N");
		automata.addTransicion(58, 23, "D");
		automata.addTransicion(58, 23, "A");
		automata.addTransicion(58, 23, "T");
		automata.addTransicion(58, 23, "S");
		automata.addTransicion(58, 23, "K");
		automata.addTransicion(58, 23, "Y");
		automata.addTransicion(58, 23, "W");
		automata.addTransicion(58, 23, "U");
		automata.addTransicion(58, 23, "X");
		automata.addTransicion(59, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(59, 24, "0123456789");
		automata.addNode(59, "C");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(59, 23, "H");
		automata.addTransicion(59, 23, "R");
		automata.addTransicion(59, 23, "O");
		automata.addTransicion(59, 23, "M");
		automata.addTransicion(59, 23, "P");
		automata.addTransicion(59, 23, "I");
		automata.addTransicion(59, 23, "L");
		automata.addTransicion(59, 23, "E");
		automata.addTransicion(59, 23, "N");
		automata.addTransicion(59, 23, "D");
		automata.addTransicion(59, 23, "A");
		automata.addTransicion(59, 23, "T");
		automata.addTransicion(59, 23, "S");
		automata.addTransicion(59, 23, "K");
		automata.addTransicion(59, 23, "Y");
		automata.addTransicion(59, 23, "W");
		automata.addTransicion(59, 23, "U");
		automata.addTransicion(59, 23, "X");
		automata.addTransicion(60, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(60, 24, "0123456789");
		automata.addTransicion(60, 23, "C");
		automata.addTransicion(60, 23, "H");
		automata.addTransicion(60, 23, "R");
		automata.addTransicion(60, 23, "O");
		automata.addTransicion(60, 23, "M");
		automata.addTransicion(60, 23, "P");
		automata.addTransicion(60, 23, "I");
		automata.addTransicion(60, 23, "L");
		automata.addTransicion(60, 23, "E");
		automata.addTransicion(60, 23, "N");
		automata.addTransicion(60, 23, "D");
		automata.addTransicion(60, 23, "A");
		automata.addNode(60, "T");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("EXCEPT");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(18);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(60, 23, "S");
		automata.addTransicion(60, 23, "K");
		automata.addTransicion(60, 23, "Y");
		automata.addTransicion(60, 23, "W");
		automata.addTransicion(60, 23, "U");
		automata.addTransicion(60, 23, "X");
		automata.addTransicion(61, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(61, 24, "0123456789");
		automata.addTransicion(61, 23, "C");
		automata.addTransicion(61, 23, "H");
		automata.addTransicion(61, 23, "R");
		automata.addTransicion(61, 23, "O");
		automata.addTransicion(61, 23, "M");
		automata.addTransicion(61, 23, "P");
		automata.addTransicion(61, 23, "I");
		automata.addTransicion(61, 23, "L");
		automata.addTransicion(61, 23, "E");
		automata.addTransicion(61, 23, "N");
		automata.addTransicion(61, 23, "D");
		automata.addTransicion(61, 23, "A");
		automata.addTransicion(61, 23, "T");
		automata.addNode(61, "S");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("TOKENS");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(16);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(61, 23, "K");
		automata.addTransicion(61, 23, "Y");
		automata.addTransicion(61, 23, "W");
		automata.addTransicion(61, 23, "U");
		automata.addTransicion(61, 23, "X");
		automata.addTransicion(62, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(62, 24, "0123456789");
		automata.addTransicion(62, 23, "C");
		automata.addTransicion(62, 23, "H");
		automata.addNode(62, "R");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(62, 23, "O");
		automata.addTransicion(62, 23, "M");
		automata.addTransicion(62, 23, "P");
		automata.addTransicion(62, 23, "I");
		automata.addTransicion(62, 23, "L");
		automata.addTransicion(62, 23, "E");
		automata.addTransicion(62, 23, "N");
		automata.addTransicion(62, 23, "D");
		automata.addTransicion(62, 23, "A");
		automata.addTransicion(62, 23, "T");
		automata.addTransicion(62, 23, "S");
		automata.addTransicion(62, 23, "K");
		automata.addTransicion(62, 23, "Y");
		automata.addTransicion(62, 23, "W");
		automata.addTransicion(62, 23, "U");
		automata.addTransicion(62, 23, "X");
		automata.addTransicion(63, 63, "0123456789");
		automata.addTransicion(63, 64, ")");
		automata.addNode(64, ".");
		automata.addTransicion(65, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(65, 24, "0123456789");
		automata.addTransicion(65, 23, "C");
		automata.addTransicion(65, 23, "H");
		automata.addTransicion(65, 23, "R");
		automata.addTransicion(65, 23, "O");
		automata.addTransicion(65, 23, "M");
		automata.addTransicion(65, 23, "P");
		automata.addTransicion(65, 23, "I");
		automata.addTransicion(65, 23, "L");
		automata.addTransicion(65, 23, "E");
		automata.addTransicion(65, 23, "N");
		automata.addTransicion(65, 23, "D");
		automata.addTransicion(65, 23, "A");
		automata.addNode(65, "T");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(65, 23, "S");
		automata.addTransicion(65, 23, "K");
		automata.addTransicion(65, 23, "Y");
		automata.addTransicion(65, 23, "W");
		automata.addTransicion(65, 23, "U");
		automata.addTransicion(65, 23, "X");
		automata.addTransicion(66, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(66, 24, "0123456789");
		automata.addTransicion(66, 23, "C");
		automata.addTransicion(66, 23, "H");
		automata.addTransicion(66, 23, "R");
		automata.addTransicion(66, 23, "O");
		automata.addTransicion(66, 23, "M");
		automata.addTransicion(66, 23, "P");
		automata.addTransicion(66, 23, "I");
		automata.addTransicion(66, 23, "L");
		automata.addNode(66, "E");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(66, 23, "N");
		automata.addTransicion(66, 23, "D");
		automata.addTransicion(66, 23, "A");
		automata.addTransicion(66, 23, "T");
		automata.addTransicion(66, 23, "S");
		automata.addTransicion(66, 23, "K");
		automata.addTransicion(66, 23, "Y");
		automata.addTransicion(66, 23, "W");
		automata.addTransicion(66, 23, "U");
		automata.addTransicion(66, 23, "X");
		automata.addTransicion(67, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(67, 24, "0123456789");
		automata.addTransicion(67, 23, "C");
		automata.addTransicion(67, 23, "H");
		automata.addTransicion(67, 23, "R");
		automata.addTransicion(67, 23, "O");
		automata.addTransicion(67, 23, "M");
		automata.addTransicion(67, 23, "P");
		automata.addTransicion(67, 23, "I");
		automata.addTransicion(67, 23, "L");
		automata.addTransicion(67, 23, "E");
		automata.addTransicion(67, 23, "N");
		automata.addTransicion(67, 23, "D");
		automata.addTransicion(67, 23, "A");
		automata.addNode(67, "T");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(67, 23, "S");
		automata.addTransicion(67, 23, "K");
		automata.addTransicion(67, 23, "Y");
		automata.addTransicion(67, 23, "W");
		automata.addTransicion(67, 23, "U");
		automata.addTransicion(67, 23, "X");
		automata.addTransicion(68, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(68, 24, "0123456789");
		automata.addTransicion(68, 23, "C");
		automata.addTransicion(68, 23, "H");
		automata.addTransicion(68, 23, "R");
		automata.addTransicion(68, 23, "O");
		automata.addTransicion(68, 23, "M");
		automata.addTransicion(68, 23, "P");
		automata.addTransicion(68, 23, "I");
		automata.addTransicion(68, 23, "L");
		automata.addTransicion(68, 23, "E");
		automata.addTransicion(68, 23, "N");
		automata.addTransicion(68, 23, "D");
		automata.addTransicion(68, 23, "A");
		automata.addTransicion(68, 23, "T");
		automata.addTransicion(68, 23, "S");
		automata.addTransicion(68, 23, "K");
		automata.addTransicion(68, 23, "Y");
		automata.addTransicion(68, 23, "W");
		automata.addTransicion(68, 23, "U");
		automata.addTransicion(68, 23, "X");
		automata.addTransicion(69, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(69, 24, "0123456789");
		automata.addTransicion(69, 23, "C");
		automata.addTransicion(69, 23, "H");
		automata.addTransicion(69, 23, "R");
		automata.addTransicion(69, 23, "O");
		automata.addTransicion(69, 23, "M");
		automata.addTransicion(69, 23, "P");
		automata.addTransicion(69, 23, "I");
		automata.addTransicion(69, 23, "L");
		automata.addTransicion(69, 23, "E");
		automata.addTransicion(69, 23, "N");
		automata.addTransicion(69, 23, "D");
		automata.addTransicion(69, 23, "A");
		automata.addTransicion(69, 23, "T");
		automata.addTransicion(69, 23, "S");
		automata.addTransicion(69, 23, "K");
		automata.addTransicion(69, 23, "Y");
		automata.addTransicion(69, 23, "W");
		automata.addTransicion(69, 23, "U");
		automata.addTransicion(69, 23, "X");
		automata.addTransicion(70, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(70, 24, "0123456789");
		automata.addTransicion(70, 23, "C");
		automata.addTransicion(70, 23, "H");
		automata.addTransicion(70, 23, "R");
		automata.addTransicion(70, 23, "O");
		automata.addTransicion(70, 23, "M");
		automata.addTransicion(70, 23, "P");
		automata.addTransicion(70, 23, "I");
		automata.addTransicion(70, 23, "L");
		automata.addTransicion(70, 23, "E");
		automata.addTransicion(70, 23, "N");
		automata.addNode(70, "D");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(70, 23, "A");
		automata.addTransicion(70, 23, "T");
		automata.addTransicion(70, 23, "S");
		automata.addTransicion(70, 23, "K");
		automata.addTransicion(70, 23, "Y");
		automata.addTransicion(70, 23, "W");
		automata.addTransicion(70, 23, "U");
		automata.addTransicion(70, 23, "X");
		automata.addNode(71, ".");
		automata.addTransicion(72, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(72, 24, "0123456789");
		automata.addTransicion(72, 23, "C");
		automata.addTransicion(72, 23, "H");
		automata.addTransicion(72, 23, "R");
		automata.addTransicion(72, 23, "O");
		automata.addTransicion(72, 23, "M");
		automata.addTransicion(72, 23, "P");
		automata.addTransicion(72, 23, "I");
		automata.addTransicion(72, 23, "L");
		automata.addNode(72, "E");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(72, 23, "N");
		automata.addTransicion(72, 23, "D");
		automata.addTransicion(72, 23, "A");
		automata.addTransicion(72, 23, "T");
		automata.addTransicion(72, 23, "S");
		automata.addTransicion(72, 23, "K");
		automata.addTransicion(72, 23, "Y");
		automata.addTransicion(72, 23, "W");
		automata.addTransicion(72, 23, "U");
		automata.addTransicion(72, 23, "X");
		automata.addTransicion(73, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(73, 24, "0123456789");
		automata.addTransicion(73, 23, "C");
		automata.addTransicion(73, 23, "H");
		automata.addNode(73, "R");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("COMPILER");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(8);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(73, 23, "O");
		automata.addTransicion(73, 23, "M");
		automata.addTransicion(73, 23, "P");
		automata.addTransicion(73, 23, "I");
		automata.addTransicion(73, 23, "L");
		automata.addTransicion(73, 23, "E");
		automata.addTransicion(73, 23, "N");
		automata.addTransicion(73, 23, "D");
		automata.addTransicion(73, 23, "A");
		automata.addTransicion(73, 23, "T");
		automata.addTransicion(73, 23, "S");
		automata.addTransicion(73, 23, "K");
		automata.addTransicion(73, 23, "Y");
		automata.addTransicion(73, 23, "W");
		automata.addTransicion(73, 23, "U");
		automata.addTransicion(73, 23, "X");
		automata.addTransicion(74, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(74, 24, "0123456789");
		automata.addTransicion(74, 23, "C");
		automata.addTransicion(74, 23, "H");
		automata.addTransicion(74, 23, "R");
		automata.addTransicion(74, 23, "O");
		automata.addTransicion(74, 23, "M");
		automata.addTransicion(74, 23, "P");
		automata.addNode(74, "I");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(74, 23, "L");
		automata.addTransicion(74, 23, "E");
		automata.addTransicion(74, 23, "N");
		automata.addTransicion(74, 23, "D");
		automata.addTransicion(74, 23, "A");
		automata.addTransicion(74, 23, "T");
		automata.addTransicion(74, 23, "S");
		automata.addTransicion(74, 23, "K");
		automata.addTransicion(74, 23, "Y");
		automata.addTransicion(74, 23, "W");
		automata.addTransicion(74, 23, "U");
		automata.addTransicion(74, 23, "X");
		automata.addTransicion(75, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(75, 24, "0123456789");
		automata.addTransicion(75, 23, "C");
		automata.addTransicion(75, 23, "H");
		automata.addTransicion(75, 23, "R");
		automata.addTransicion(75, 23, "O");
		automata.addTransicion(75, 23, "M");
		automata.addTransicion(75, 23, "P");
		automata.addTransicion(75, 23, "I");
		automata.addTransicion(75, 23, "L");
		automata.addTransicion(75, 23, "E");
		automata.addTransicion(75, 23, "N");
		automata.addTransicion(75, 23, "D");
		automata.addTransicion(75, 23, "A");
		automata.addTransicion(75, 23, "T");
		automata.addNode(75, "S");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("KEYWORDS");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(15);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(75, 23, "K");
		automata.addTransicion(75, 23, "Y");
		automata.addTransicion(75, 23, "W");
		automata.addTransicion(75, 23, "U");
		automata.addTransicion(75, 23, "X");
		automata.addNode(76, "C");
		automata.addTransicion(77, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(77, 24, "0123456789");
		automata.addTransicion(77, 23, "C");
		automata.addTransicion(77, 23, "H");
		automata.addNode(77, "R");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(77, 23, "O");
		automata.addTransicion(77, 23, "M");
		automata.addTransicion(77, 23, "P");
		automata.addTransicion(77, 23, "I");
		automata.addTransicion(77, 23, "L");
		automata.addTransicion(77, 23, "E");
		automata.addTransicion(77, 23, "N");
		automata.addTransicion(77, 23, "D");
		automata.addTransicion(77, 23, "A");
		automata.addTransicion(77, 23, "T");
		automata.addTransicion(77, 23, "S");
		automata.addTransicion(77, 23, "K");
		automata.addTransicion(77, 23, "Y");
		automata.addTransicion(77, 23, "W");
		automata.addTransicion(77, 23, "U");
		automata.addTransicion(77, 23, "X");
		automata.addTransicion(78, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(78, 24, "0123456789");
		automata.addTransicion(78, 23, "C");
		automata.addTransicion(78, 23, "H");
		automata.addTransicion(78, 23, "R");
		automata.addTransicion(78, 23, "O");
		automata.addTransicion(78, 23, "M");
		automata.addTransicion(78, 23, "P");
		automata.addTransicion(78, 23, "I");
		automata.addTransicion(78, 23, "L");
		automata.addTransicion(78, 23, "E");
		automata.addTransicion(78, 23, "N");
		automata.addTransicion(78, 23, "D");
		automata.addTransicion(78, 23, "A");
		automata.addTransicion(78, 23, "T");
		automata.addTransicion(78, 23, "S");
		automata.addTransicion(78, 23, "K");
		automata.addTransicion(78, 23, "Y");
		automata.addTransicion(78, 23, "W");
		automata.addTransicion(78, 23, "U");
		automata.addTransicion(78, 23, "X");
		automata.addTransicion(79, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(79, 24, "0123456789");
		automata.addTransicion(79, 23, "C");
		automata.addTransicion(79, 23, "H");
		automata.addTransicion(79, 23, "R");
		automata.addNode(79, "O");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(79, 23, "M");
		automata.addTransicion(79, 23, "P");
		automata.addTransicion(79, 23, "I");
		automata.addTransicion(79, 23, "L");
		automata.addTransicion(79, 23, "E");
		automata.addTransicion(79, 23, "N");
		automata.addTransicion(79, 23, "D");
		automata.addTransicion(79, 23, "A");
		automata.addTransicion(79, 23, "T");
		automata.addTransicion(79, 23, "S");
		automata.addTransicion(79, 23, "K");
		automata.addTransicion(79, 23, "Y");
		automata.addTransicion(79, 23, "W");
		automata.addTransicion(79, 23, "U");
		automata.addTransicion(79, 23, "X");
		automata.addTransicion(80, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(80, 24, "0123456789");
		automata.addTransicion(80, 23, "C");
		automata.addTransicion(80, 23, "H");
		automata.addTransicion(80, 23, "R");
		automata.addTransicion(80, 23, "O");
		automata.addTransicion(80, 23, "M");
		automata.addTransicion(80, 23, "P");
		automata.addTransicion(80, 23, "I");
		automata.addTransicion(80, 23, "L");
		automata.addTransicion(80, 23, "E");
		automata.addTransicion(80, 23, "N");
		automata.addTransicion(80, 23, "D");
		automata.addTransicion(80, 23, "A");
		automata.addTransicion(80, 23, "T");
		automata.addTransicion(80, 23, "S");
		automata.addTransicion(80, 23, "K");
		automata.addTransicion(80, 23, "Y");
		automata.addTransicion(80, 23, "W");
		automata.addTransicion(80, 23, "U");
		automata.addTransicion(80, 23, "X");
		automata.addNode(81, "H");
		automata.addTransicion(82, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(82, 24, "0123456789");
		automata.addTransicion(82, 23, "C");
		automata.addTransicion(82, 23, "H");
		automata.addTransicion(82, 23, "R");
		automata.addTransicion(82, 23, "O");
		automata.addTransicion(82, 23, "M");
		automata.addTransicion(82, 23, "P");
		automata.addTransicion(82, 23, "I");
		automata.addTransicion(82, 23, "L");
		automata.addTransicion(82, 23, "E");
		automata.addTransicion(82, 23, "N");
		automata.addTransicion(82, 23, "D");
		automata.addTransicion(82, 23, "A");
		automata.addTransicion(82, 23, "T");
		automata.addNode(82, "S");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("CHARACTERS");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(10);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(82, 23, "K");
		automata.addTransicion(82, 23, "Y");
		automata.addTransicion(82, 23, "W");
		automata.addTransicion(82, 23, "U");
		automata.addTransicion(82, 23, "X");
		automata.addTransicion(83, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(83, 24, "0123456789");
		automata.addTransicion(83, 23, "C");
		automata.addTransicion(83, 23, "H");
		automata.addTransicion(83, 23, "R");
		automata.addTransicion(83, 23, "O");
		automata.addTransicion(83, 23, "M");
		automata.addTransicion(83, 23, "P");
		automata.addTransicion(83, 23, "I");
		automata.addTransicion(83, 23, "L");
		automata.addTransicion(83, 23, "E");
		automata.addNode(83, "N");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("ident");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(0);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(83, 23, "D");
		automata.addTransicion(83, 23, "A");
		automata.addTransicion(83, 23, "T");
		automata.addTransicion(83, 23, "S");
		automata.addTransicion(83, 23, "K");
		automata.addTransicion(83, 23, "Y");
		automata.addTransicion(83, 23, "W");
		automata.addTransicion(83, 23, "U");
		automata.addTransicion(83, 23, "X");
		automata.addNode(84, "R");
		automata.addTransicion(85, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(85, 24, "0123456789");
		automata.addTransicion(85, 23, "C");
		automata.addTransicion(85, 23, "H");
		automata.addTransicion(85, 23, "R");
		automata.addTransicion(85, 23, "O");
		automata.addTransicion(85, 23, "M");
		automata.addTransicion(85, 23, "P");
		automata.addTransicion(85, 23, "I");
		automata.addTransicion(85, 23, "L");
		automata.addTransicion(85, 23, "E");
		automata.addTransicion(85, 23, "N");
		automata.addTransicion(85, 23, "D");
		automata.addTransicion(85, 23, "A");
		automata.addTransicion(85, 23, "T");
		automata.addTransicion(85, 23, "S");
		automata.addTransicion(85, 23, "K");
		automata.addTransicion(85, 23, "Y");
		automata.addTransicion(85, 23, "W");
		automata.addTransicion(85, 23, "U");
		automata.addTransicion(85, 23, "X");
		automata.addTransicion(86, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(86, 24, "0123456789");
		automata.addTransicion(86, 23, "C");
		automata.addTransicion(86, 23, "H");
		automata.addTransicion(86, 23, "R");
		automata.addTransicion(86, 23, "O");
		automata.addTransicion(86, 23, "M");
		automata.addTransicion(86, 23, "P");
		automata.addTransicion(86, 23, "I");
		automata.addTransicion(86, 23, "L");
		automata.addTransicion(86, 23, "E");
		automata.addTransicion(86, 23, "N");
		automata.addTransicion(86, 23, "D");
		automata.addTransicion(86, 23, "A");
		automata.addTransicion(86, 23, "T");
		automata.addNode(86, "S");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("PRODUCTIONS");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(17);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(86, 23, "K");
		automata.addTransicion(86, 23, "Y");
		automata.addTransicion(86, 23, "W");
		automata.addTransicion(86, 23, "U");
		automata.addTransicion(86, 23, "X");
		automata.addNode(87, "(");
		automata.addTransicion(88, 23, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
		automata.addTransicion(88, 24, "0123456789");
		automata.addTransicion(88, 23, "C");
		automata.addTransicion(88, 23, "H");
		automata.addTransicion(88, 23, "R");
		automata.addTransicion(88, 23, "O");
		automata.addTransicion(88, 23, "M");
		automata.addTransicion(88, 23, "P");
		automata.addTransicion(88, 23, "I");
		automata.addTransicion(88, 23, "L");
		automata.addTransicion(88, 23, "E");
		automata.addTransicion(88, 23, "N");
		automata.addTransicion(88, 23, "D");
		automata.addTransicion(88, 23, "A");
		automata.addTransicion(88, 23, "T");
		automata.addTransicion(88, 23, "S");
		automata.addTransicion(88, 23, "K");
		automata.addTransicion(88, 23, "Y");
		automata.addTransicion(88, 23, "W");
		automata.addTransicion(88, 23, "U");
		automata.addTransicion(88, 23, "X");
		automata.addNode(89, "0123456789");
		automata.addNode(90, "0123456789");
		automata.addNode(90, ")");
		automata.getNodo(automata.getCantidadNodos()-1).setIsFinal(true);
		automata.getNodo(automata.getCantidadNodos()-1).setToken("charinterval");
		automata.getNodo(automata.getCantidadNodos()-1).setTokenNumber(4);
		automata.getNodo(automata.getCantidadNodos()-1).setTokenType(1);
		automata.addTransicion(91, 91, "0123456789");
		automata.addTransicion(91, 92, ")");
    }}
